### PR TITLE
fix: the stored last n headers is less than expected

### LINKED ISSUE #117: Long fork detected when long-time working
commit: c24c3edb2a01140bf3ad636daa0dd27fa268c82b
config.toml
```
# chain = "mainnet"
# chain = "testnet"
# chain = "your_path_to/dev.toml"
chain = "testnet"

[store]
path = "data/store"

[network]
path = "data/network"

listen_addresses = ["/ip4/0.0.0.0/tcp/8118"]
### Specify the public and routable network addresses
# public_addresses = []

# Node connects to nodes listed here to discovery other peers when there's no local stored peers.
# When chain.spec is changed, this usually should also be changed to the bootnodes in the new chain.
bootnodes = [
 # Hangzhou, Asia
  "/ip4/47.111.169.36/tcp/8111/p2p/QmNQ4jky6uVqLDrPU7snqxARuNGWNLgSrTnssbRuy3ij2W",
  # Ohio, North America
  "/ip4/18.217.146.65/tcp/8111/p2p/QmT6DFfm18wtbJz3y4aPNn3ac86N4d4p4xtfQRRPf73frC",
  # Singapore, Asia
  "/ip4/18.136.60.221/tcp/8111/p2p/QmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb",
  # London, Europe
  "/ip4/35.176.207.239/tcp/8111/p2p/QmSJTsMsMGBjzv1oBNwQU36VhQRxc2WQpFoRu1ZifYKrjZ"
]

### Whitelist-only mode
whitelist_only = true
### Whitelist peers connecting from the given IP addresses
whitelist_peers = [
# Hangzhou, Asia
  "/ip4/47.111.169.36/tcp/8111/p2p/QmNQ4jky6uVqLDrPU7snqxARuNGWNLgSrTnssbRuy3ij2W",
  # Ohio, North America
  "/ip4/18.217.146.65/tcp/8111/p2p/QmT6DFfm18wtbJz3y4aPNn3ac86N4d4p4xtfQRRPf73frC",
  # Singapore, Asia
  "/ip4/18.136.60.221/tcp/8111/p2p/QmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb",
  # London, Europe
  "/ip4/35.176.207.239/tcp/8111/p2p/QmSJTsMsMGBjzv1oBNwQU36VhQRxc2WQpFoRu1ZifYKrjZ"
]

max_peers = 5000
max_outbound_peers = 2500
# 2 minutes
ping_interval_secs = 120
# 20 minutes
ping_timeout_secs = 1200
connect_outbound_interval_secs = 15
# If set to true, try to register upnp
upnp = false
# If set to true, network service will add discovered local address to peer store, it's helpful for private net development
discovery_local_address = false
# If set to true, random cleanup when there are too many inbound nodes
# Ensure that itself can continue to serve as a bootnode node
bootnode_mode = false

[rpc]
# Light client rpc is designed for self hosting, exposing to public network is not recommended and may cause security issues.
# By default RPC only binds to localhost, thus it only allows accessing from the same machine.
listen_address = "127.0.0.1:9000"
```
### step 
1. setScript
2. hang up for a long time

### response
1. collect script msg
2. the node reports an error Long fork detected
```
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x4b33d8a7a00a7fa056d93f477a95177b9b33dda8623b26eba17f84bd777920ba
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0xdabf2dfc4a16c5f5a7b3ddd50da5d8fdc73496665dd87421cf2401ae79f342ff
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0xfda36b1957e4878bcd9d95ee089d28f446999a9af2f500ecd0dfba561a678c1f
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0xfb8313ac528cc6ec218d610eb7917af6a8144faca190fb2e609889d2043ecb3c
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x3d8d1eda4d01228dd2a6955b4d481e2b1266b66e3536ab2297e2fe1a956a4b22
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x109e5857e30ab7667808837dc82407099b89d0f60fd1ef55775b4b1bd2c6da6b
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0xd219f9031cff3bf652b50b7b1cbd3f5e38f91c317b9c7eb00cdbc7c994f1e090
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x85cd1a46a127ea2bd39e3583a481b575c1e01d606e53b491b69fc38e463a515a
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x2d643eb8edcb7ed8b005c05a4ed1f977f11bc56305daae7e518a4adbb975d703
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x54d59309292a4825d0754e8f4185df1f5cd683629e50c2adfc1220584636e31c
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x6a5d9125da39b800b11fd1e08b07d7acf5ff9591c97921efd68900c77b22e191
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] check_filters_data not matched, block_hash: 0x916ed3be65b2d25f48b25bc1a047c48bbdd219d1460dd298af0488cfe0bd1931
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::components::block_filters_process] peer SessionId(4), matched blocks: 0
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::filter::block_filter] FilterProtocol.received peer=SessionId(4), message=BlockFilters
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client] peer SessionId(2): send get last state proof
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state] peer SessionId(1): update last state
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client] LightClient.received peer=SessionId(1), message=SendLastState
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state] peer SessionId(2): update last state
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client] LightClient.received peer=SessionId(2), message=SendLastState
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state_proof] peer SessionId(2): headers count: reorg: 100, sampled: 0, last_n: 5
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state_proof] peer SessionId(2) skip checking TAU since no sampled headers
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state_proof] passed: verify extra hash for block-7916468 (0x294109f63850f6ffbc9189f1e9955e8dc6f3bc5d98195b2759a6661b694d71a2)
[2023-01-06T09:09:27Z TRACE ckb_light_client::protocols::light_client::components::send_last_state_proof] passed: verify mmr proof
[2023-01-06T09:09:27Z ERROR ckb_light_client::protocols::light_client] Long fork detected, please check if ckb-light-client is connected to the same network ckb node. If you connected ckb-light-client to a dev chain for testing purpose you should remove the storage of ckb-light-client to recover.
thread 'GlobalRt-0' panicked at 'long fork detected', src/protocols/light_client/mod.rs:353:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-01-06T09:09:27Z INFO  ckb_network::network] p2p service event: ListenClose { address: "/ip4/0.0.0.0/tcp/8118" }
[2023-01-06T09:09:27Z INFO  ckb_light_client::protocols::synchronizer] SyncProtocol.disconnected peer=SessionId(1)
[2023-01-06T09:09:27Z INFO  ckb_light_client::protocols::synchronizer] SyncProtocol.disconnected peer=SessionId(2)
[2023-01-06T09:09:27Z INFO  ckb_light_client::protocols::synchronizer] SyncProtocol.disconnected peer=SessionId(3)
[2023-01-06T09:09:27Z DEBUG ckb_light_client::protocols::filter::block_filter] FilterProtocol.disconnected peer=SessionId(1)
[2023-01-06T09:09:27Z DEBUG ckb_light_client::protocols::filter::block_filter] FilterProtocol.disconnected peer=SessionId(2)
[2023-01-06T09:09:27Z DEBUG ckb_light_client::protocols::filter::block_filter] FilterProtocol.disconnected peer=SessionId(3)
[2023-01-06T09:09:27Z DEBUG ckb_light_client::protocols::filter::block_filter] FilterProtocol.disconnected peer=SessionId(4)
[2023-01-06T09:09:27Z INFO  ckb_light_client::protocols::synchronizer] SyncProtocol.disconnected peer=SessionId(4)
[2023-01-06T09:09:27Z INFO  ckb_stop_handler] StopHandler(network) 

```

### PR DESCRIPTION
**Pull request by chaoticlonghair**
### Issue

Let $N_{last}$ denote the constant `LAST_N_BLOCKS`.

Suppose there are follow steps:

- Start a light client `C`.

- `C` connected to a CKB node `N`.

- `C` gets last state of block $h_{1}$ and its proof from `N`.

  And `C` saves $N_{last}$ last-N headers in its storage.

- The last state from `N` changes to $h_{2}$ with $h_{2}  = h_{1} + t$ and $N_{last} \gt t \gt 1$.

The bug is:

- When `C` updates the last state from $h_{1}$ to $h_{2}$, the count of saved last-N headers in the storage will changed to $t$.

- Then, if $t$ is too small, it will be difficult to find the ancestor block for a fork chain.

- So long fork will be detected frequently.

### Updates

- When add proved blocks, 

  - if the count of new last N headers is **less than** the expected count of the last N blocks, just **copy some old last N headers** to make sure we have enough stored last N headers.

  - if the count of new last N headers is **greater than** the expected count of the last N blocks, just **remove some of them** to avoid unlimited memory growth.

- Refactor unit tests to make it easier to add an `assert` to several unit tests, not just copy the code several times.

  And also add more unit tests to improve the coverage.

Resolve #117.

### CODE REVIEW

File: src/tests/protocols/light_client/send_last_state_proof.rs [hunk 1]
```diff
@@ -1120,94 +1356,432 @@ async fn invalid_proof() {
...
+            .expect("has peer state")
+            .get_prove_state()
+            .expect("has prove state")
+            .to_owned();
+        let last_header: VerifiableHeader = last_header.into();
+        assert!(prove_state.is_same_as(&last_header));
+        let expected_last_headers_count = param
+            .expected_last_headers_count_opt
+            .unwrap_or(last_n_blocks) as usize;
+        assert_eq!(
```
Comment (yangby-cryptape) [inline src/tests/protocols/light_client/send_last_state_proof.rs:1377]: The checks for the stored last N headers in unit tests.

File: src/tests/protocols/light_client/send_last_state_proof.rs [hunk 2]
```diff
@@ -1925,197 +1823,69 @@ async fn reorg_rollback_blocks(rollback_blocks_num: u64) {
...
+        } else {
+            assert!(!prove_state.get_reorg_last_headers().is_empty());
+        }
         assert!(prove_state.is_same_as(&last_header));
-        let min_filtered_block_number = if rollback_blocks_num == 0 {
-            prev_last_number - 1
+        let expected_last_headers_count = param
+            .expected_last_headers_count_opt
+            .unwrap_or(last_n_blocks) as usize;
+        assert_eq!(
```
Comment (yangby-cryptape) [inline src/tests/protocols/light_client/send_last_state_proof.rs:1835]: The checks for the stored last N headers in unit tests.

File: src/protocols/light_client/components/send_last_state_proof.rs [hunk 3]
```diff
@@ -179,20 +181,62 @@ impl<'a> SendLastStateProofProcess<'a> {
...
+                            new_last_headers
+                        } else {
+                            let required_count = last_n_blocks - last_n_count;
+                            let old_last_headers_len = old_last_headers.len();
+                            if old_last_headers_len > required_count {
+                                let split_at = old_last_headers_len - required_count;
+                                old_last_headers = old_last_headers.split_at(split_at).1;
+                            }
+                            old_last_headers
+                                .iter()
```
Comment (quake) [inline src/protocols/light_client/components/send_last_state_proof.rs:222]: suggest to use `iterator#skip`

```suggestion
                            old_last_headers
                                .iter()
                                .skip(old_last_headers_len.saturating_sub(required_count))
```

**Review by quake — CHANGES_REQUESTED** [review]

File: src/protocols/light_client/components/send_last_state_proof.rs [hunk 4]
```diff
@@ -179,20 +181,62 @@ impl<'a> SendLastStateProofProcess<'a> {
...
+                }
+                Ordering::Less => {
+                    if let Some(prove_state) = peer_state.get_prove_state() {
+                        let mut old_last_headers = if reorg_count == 0 {
+                            prove_state.get_last_headers()
+                        } else {
+                            &headers[..reorg_count]
+                        };
+                        // last_headers from previous prove state are empty
+                        // iff the chain only has 1 block after MMR enabled.
```
[the remark this answers is not in the document]
Comment (yangby-cryptape) [reply src/protocols/light_client/components/send_last_state_proof.rs:211]: Common abbreviation of "if and only if".

**Review by quake — APPROVED** [review]
